# Generated by Django 5.2 on 2026-03-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("severity", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], default="MEDIUM", max_length=16)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("INVESTIGATING", "Investigating"), ("ROOT_CAUSE_IDENTIFIED", "Root cause identified"), ("ACTIONS_IN_PROGRESS", "Actions in progress"), ("VERIFIED", "Verified"), ("CLOSED", "Closed")], default="OPEN", max_length=32)),
                ("occurred_at", models.DateTimeField(blank=True, help_text="When the defect occurred (optional).", null=True)),
                ("due_date", models.DateField(blank=True, help_text="Target date for resolution (optional).", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_defects", to=settings.AUTH_USER_MODEL)),
                ("reported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reported_defects", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RootCause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("NOT_STARTED", "Not started"), ("IN_PROGRESS", "In progress"), ("IDENTIFIED", "Identified"), ("APPROVED", "Approved")], default="NOT_STARTED", max_length=16)),
                ("summary", models.TextField(blank=True, default="")),
                ("analysis", models.TextField(blank=True, default="")),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("defect", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="root_cause", to="api.defect")),
                ("identified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="root_causes_identified", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("IN_PROGRESS", "In progress"), ("DONE", "Done"), ("VERIFIED", "Verified"), ("CANCELED", "Canceled")], default="OPEN", max_length=16)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("defect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corrective_actions", to="api.defect")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_corrective_actions", to=settings.AUTH_USER_MODEL)),
                ("root_cause", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="corrective_actions", to="api.rootcause")),
            ],
        ),
    ]
