# Generated by Django 5.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="area",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Business/production area where the defect occurred (UI field).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="assigned_to_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text 'Assigned to' captured by UI (not tied to auth users).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="priority",
            field=models.CharField(
                blank=True,
                default="P3",
                help_text="UI priority label (P1, P2, P3).",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="reporter_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text 'Reported by' captured by UI (not tied to auth users).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="tags",
            field=models.JSONField(blank=True, default=list, help_text="List of tag strings (UI field)."),
        ),
    ]
