# Generated by Django 5.2 on 2026-03-25
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_rootcause_and_history(apps, schema_editor):
    """Backfill for existing records.

    - Ensure every Defect has a RootCause row (to support gating and 5-Why UI).
    - Create an initial DefectStatusHistory entry for each defect that has none.
    """
    Defect = apps.get_model("api", "Defect")
    RootCause = apps.get_model("api", "RootCause")
    DefectStatusHistory = apps.get_model("api", "DefectStatusHistory")

    # 1) RootCause: create if missing (defaults: NOT_STARTED, empty text fields)
    # Use iterator() to avoid loading all defects into memory.
    for defect in Defect.objects.all().only("id").iterator():
        RootCause.objects.get_or_create(defect_id=defect.id)

    # 2) Status history: seed an initial entry if none exists.
    # We don't know historical transitions, but we at least capture current status.
    # from_status left blank to denote "unknown/initial".
    for defect in Defect.objects.all().only("id", "status").iterator():
        has_any = (
            DefectStatusHistory.objects.filter(defect_id=defect.id).only("id").exists()
        )
        if not has_any:
            DefectStatusHistory.objects.create(
                defect_id=defect.id,
                from_status="",
                to_status=defect.status,
                changed_by_id=None,
                note="Backfilled initial status at migration time.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_defect_display_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rootcause",
            name="why_1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rootcause",
            name="why_2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rootcause",
            name="why_3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rootcause",
            name="why_4",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rootcause",
            name="why_5",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="DefectStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defect_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="api.defect",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.RunPython(
            backfill_rootcause_and_history, reverse_code=migrations.RunPython.noop
        ),
    ]
